USE DR_CAQUI_DB;
GO

INSERT INTO tipoUsuario VALUES('Administrador'), ('Responsavel'), ('Profissional da Saúde');
GO

INSERT INTO raca VALUES ('Branca'), ('Negra'), ('Amarela'), ('Parda'), ('Indígena');

INSERT INTO mchat VALUES ('Postura: pernas e braços fletidos, cabeça lateralizada','Deite a criança em superfície plana, de costas, com a barriga para cima; observe se seus braços e pernas ficam flexionados e sua cabeça lateralizada.', 1),
('Observa um rosto','Posicione seu rosto a aproximadamente 30 cm acima do rosto da criança. Observe se a criança olha para você, de forma evidente.', 1),
('Reage ao som','Fique atrás da criança e bata palmas ou balance um chocalho a cerca de 30 cm de cada orelha da criança e observe se ela reage ao estímulo sonoro com movimentos nos olhos ou  mudança da expressão facial', 1),
('Eleva a cabeça','Coloque a criança de bruços (barriga para baixo) e observe se ela levanta a cabeça, desencosta o queixo da superfície, sem virar para um dos lados.', 1),
('Sorri quando estimulada','Sorria e converse com a criança; não lhe faça cócegas ou toque sua face. Observe se ela  responde com um sorriso', 2),
('Abre as mãos','Observe se em alguns momentos a criança abre as mãos espontaneamente.', 2),
('Emite sons','Observe se a criança emite algum som, que não seja choro. Caso não seja observado pergunte ao acompanhante se faz em casa', 2),
('Movimenta  os membros','Observe se a criança movimenta ativamente os membros superiores e inferiores', 2),
('Responde ativamente ao contato social','Fique à frente do bebê e converse com ele. Observe se ele responde com sorriso e emissão de sons como se estivesse “conversando” com você. Pode pedir que a mãe o faça.', 4),
('Segura objetos','Ofereça um objeto tocando no dorso da mão ou dedos da criança. Esta deverá abrir as mãos e segurar o objeto pelo menos  por alguns segundos.', 4),
('Emite sons, ri alto','Fique à frente da criança e converse com ela. Observe se ela emite sons (gugu, eeee etc.), veja se ela ri emitindo sons (gargalhada)', 4),
('Levanta a cabeça e apoia-se nos antebraços, de bruços.','Coloque a criança de bruços, numa superfície firme. Chame sua atenção a frente com objetos ou seu rosto e observe se ela  levanta a cabeça apoiando-se nos antebraços.', 4),
('Busca ativa de objetos','Coloque um objeto ao alcance da criança (sobre a mesa ou na palma de sua mão) chamando sua atenção para ele. Observe se ela tenta alcançá-lo.', 6),
('Leva objetos a boca','Ofereça um objeto na mão da criança e observe se ela o leva a boca.', 6),
('Localiza o som','Faça um barulho suave (sino, chocalho etc.) próximo à orelha da criança  e observe se ela vira a cabeça em direção ao objeto que produziu o som. Repita no lado oposto', 6),
('Muda de posição (rola)','Coloque a criança em superfície plana de barriga para cima. Incentive-a a virar para a posição de bruços.', 6),
('Brinca de esconde-achou','Coloque-se à frente da criança e brinque de aparecer e desaparecer, atrás de um pano ou de outra pessoa. Observe se a criança faz movimentos para procurá-lo quando desaparece, como tentar puxar o pano ou olhar atrás da outra pessoa', 9),
('Transfere objetos de uma mão para outra','Ofereça um objeto para que a criança segure. Observe se ela o transfere de uma mão para outra. Se não fizer, ofereça outro objeto e observe se ela transfere o primeiro para outra mão.', 9),
('Duplica sílabas','Observe se a criança fala “papá”, “dadá”,”mamã”. Se não o fizer, pergunte a mãe se o faz em casa', 9),
('Senta-se sem apoio','Coloque a criança numa superfície firme, ofereça-lhe um objeto para que ela segure e observe se ela fica sentada sem o apoio das mãos para equilibrar-se.', 9),
('Imita gestos','Faça algum gesto conhecido pela criança como bater palmas ou dar tchau e observe se ela o imita. Caso ela não o faça, peça a mãe para estimulá-la.', 12),
('Faz pinça','Coloque próximo à criança um objeto pequeno ou uma bolinha de papel. Chame atenção da criança para que ela o pegue. Observe se ao pegá-lo ela usa o movimento de pinça, com qualquer parte do polegar associado ao indicador.', 12),
('Produz “jargão”','Observe se a criança produz uma conversação incompreensível consigo mesma, com você ou com a mãe (jargão). Caso não seja possível observar, pergunte se ela o faz em casa.', 12),
('Anda com apoio','Observe se a criança consegue dar alguns passos com apoio', 12),
('Mostra o que quer','A criança indica o que quer sem que seja por meio do choro, podendo ser por meio de palavras ou sons, apontando ou estendendo a mão para alcançar. Considerar a informação do acompanhante', 15),
('Coloca blocos na caneca','Coloque três blocos e a caneca sobre a mesa, em frente à criança. Estimule-a a colocar os blocos dentro da caneca, por meio de demonstração e fala. Observe se a criança consegue  colocar  pelo menos um bloco dentro da caneca e soltá-lo', 15),
('Diz uma palavra','Observe se durante o atendimento a criança diz pelo menos uma palavra que não seja nome de membros da família ou de animais de estimação. Considere a informação do acompanhante', 15),
('Anda sem apoio','Observe se a criança já anda bem, com bom equilíbrio, sem se apoiar. ', 15),
('Usa colher ou garfo','A criança usa colher ou garfo, derramando pouco fora da boca. Considere a informação do acompanhante.', 18),
('Constrói torre de 2 cubo','Observe se a criança consegue colocar um cubo sobre o outro sem que ele caia ao retirar sua mão.', 18),
('Fala  3  palavras','Observe se durante o atendimento a criança diz  três  palavras que não sejam nome de membros da família ou de animais de estimação. Considere a informação do acompanhante.', 18),
('Anda para trás','Peça à criança para abrir uma porta ou gaveta e observe se ela dá dois passos para trás sem cair.', 18),
('Tira roupa','Observe se criança é capaz de remover alguma peça de roupa, tais como: sapatos que exijam esforço para sua remoção, casacos, calças ou camisetas. Considerar informação do acompanhante.', 24),
('Constrói torre de 3 cubos','Observe se a criança consegue empilhar três cubos sem que eles caiam ao retirar sua mão.', 24),
('Aponta 2 figuras','Observe se a criança é capaz de apontar duas de um grupo de cinco figuras.', 24),
('Chuta bola','Observe se a criança chuta a bola sem apoiar-se em objetos.', 24),
('Veste-se com supervisão','Pergunte aos cuidadores se a criança é capaz de vestir alguma peça de roupa tais como: calcinha, cueca, meias, sapatos, casaco etc', 30),
('Constrói torre de 6 cubos','Observe se a criança consegue empilhar seis cubos sem que eles caiam ao retirar sua mão', 30),
('Frases com 2 palavras','Observe se a criança combina pelo menos duas palavras formando uma frase com significado que indique uma ação, tais como:  “quer água”, “quer papar”, “chuta bola”. Considere a informação do acompanhante.', 30),
('Pula com ambos os pés','Observe se pula com os dois pés, atingindo o chão ao mesmo tempo, mas não necessariamente no mesmo lugar.', 30),
('Brinca com outras crianças','Pergunte ao acompanhante se a criança participa de brincadeiras com outras crianças de sua idade', 36),
('Imita o desenho de uma linha','Observe, após demonstração, se a criança faz uma linha ou mais (no papel), de pelo menos 5 cm de comprimento.', 36),
('Reconhece 2 ações','Observe se a criança aponta a figura de acordo com a ação, tais como: “quem mia?” “quem late?”, “ quem fala?”, “quem galopa?”', 36),
('Arremessa bola','Observe se a criança arremessa a bola acima do braço', 36),
('Veste uma camiseta','Pergunte aos cuidadores se a criança é capaz de vestir sua camiseta e/ou casaco sem botão ou zíper, sem ajuda.', 42),
('Move o polegar com a mão fechada','Demonstre para a criança e observe se ela é capaz de mover o polegar para cima em sinal de “OK” ou “legal” ou “tudo bem”, com uma ou ambas as mãos. ',42),
('Compreende 2 adjetivos','Verifique se a criança é capaz de compreender dois adjetivos. Pergunte: “O que você faz quando está com fome?” , “O que você faz quando está com frio?” , “O que você faz quando está cansado?”. Verifique se suas respostas são coerentes, tais como: “Eu como”, “Eu visto casaco”, “Eu vou deitar” etc.', 42),
('Equilibra-se em cada pé 1 segundo','Verifique se a criança é capaz de compreender dois adjetivos. Pergunte: “O que você faz quando está com fome?” , “O que você faz quando está com frio?” , “O que você faz quando está cansado?”. Verifique se suas respostas são coerentes, tais como: “Eu como”, “Eu visto casaco”, “Eu vou deitar” etc.', 42),
('Emparelha cores','Observe se a criança é capaz de emparelhar objetos da mesma cor, por exemplo os cubos.', 48),
('Copia círculos','Forneça à criança um lápis e uma folha de papel. Mostre-lhe a figura de um círculo e verifique se ela é capaz de desenhar qualquer forma de aproximação com um círculo, que esteja fechada ou quase fechada.', 48),
('Fala clara e compreensível','Durante a avaliação observe a inteligibilidade da fala da criança (articulação e verbalização de ideias em sequência).', 48),
('Fala clara e compreensível','Durante a avaliação observe a inteligibilidade da fala da criança (articulação e verbalização de ideias em sequência).', 48),
('Pula em um pé só','Demonstre e verifique se a criança consegue pular em um pé só, duas ou mais vezes, sem apoiar-se em um objeto.', 48),
('Veste-se sem ajuda','Pergunte aos cuidadores se a criança é capaz de se vestir, sem alguma ajuda.', 54),
('Copia  cruz','Forneça à criança um lápis e uma folha de papel. Mostre-lhe a figura de  uma cruz  e verifique se ela é capaz de desenhar duas linhas que se cruzem próximo ao seu ponto médio.', 54),
('Compreende 4 preposições','Dê à criança um bloco e peça: “Coloque o bloco em cima da mesa”, “Coloque o bloco embaixo da mesa”, “Coloque um bloco na minha frente”, “Coloque um bloco atrás de mim”. Observe se ela cumpre adequadamente os quatro comandos.', 54),
('Equilibra-se em cada pé 3 segundos','Procedimento semelhante a “Equilibra-se em cada pé 1 segundo” com o tempo de 3 segundos ou mais.', 54),
('Escova dentes sem ajuda','Pergunte aos cuidadores se a criança é capaz de escovar os dentes, sem ajuda ou supervisão (durante algum tempo), inclusive na colocação da pasta de dentes, na escovação dos dentes posteriores e no uso do fio dental. Verifique se a criança recebeu treino para isso.', 60),
('Aponta a linha mais comprida','Mostre para a criança uma ficha contendo o desenho de  duas linhas paralelas em posição vertical. Verifique se ela é capaz de apontar a linha mais comprida, mesmo mudando a posição do papel. Em três tentativas, mudando a posição do papel, ela deve acertar as três, ou cinco em seis tentativas.', 60),
('Define 5 palavras','Verifique se a criança é capaz de definir cinco palavras.  Faça perguntas do tipo “O que é uma bola?” ou “O que você sabe sobre o rio?”. Use palavras do seu contexto de vida. Terá que lhe responder cinco  de sete palavras. A definição é aceitável quando inclui: 1) uso; 2) forma; 3) material do que é feito; 4) categoria geral. Ex.: Rio= tem peixe, água, pescar.', 60),
('Equilibra-se em um pé 5 segundos','Procedimento semelhante a “Equilibra-se em cada pé 1 segundo” com o tempo de 5 segundos ou mais.', 60),
('Brinca de fazer de conta com outras crianças','Pergunte aos cuidadores se a criança participa de brincadeiras de fazer de conta (ex.: casinha, escola), tanto no contexto familiar quanto no escolar.', 66),
('Desenha pessoa com 6 partes','Forneça à criança um lápis e uma folha de papel (sem pauta). Peça a ela para que desenhe uma pessoa (menino, menina, mamãe, papai etc.). Certifique-se de que ela tenha terminado o desenho antes de pontuar o item do teste. As partes do corpo presentes em pares deverão ser consideradas como uma parte apenas (orelhas, olhos, braços, mãos, pernas e pés). Considere como certo somente se ambas as partes do par forem desenhadas.', 66),
('Faz analogia','Pergunte à criança, devagar e distintamente, uma questão de cada vez: “Se o cavalo é grande, o rato é…”, “Se o fogo é quente, o gelo é…”, “Se o Sol brilha durante o dia, a lua brilha durante…” A criança deverá completar corretamente duas das três frases.', 66),
('Marcha ponta-calcanhar','Demonstre à criança como andar em linha reta, encostando a ponta de um pé no calcanhar do outro. Ande aproximadamente oito passos desta forma, e então peça para que a criança o imite. Se necessário, demonstre várias vezes (pode se facilitar a compreensão, comparando-se este andar com o “andar na corda bamba”). Até três tentativas são permitidas. Se a criança conseguir dar quatro ou mais passos em linha reta, com o calcanhar a, no máximo, 2,5 cm da ponta do pé, sem apoiar-se, terá alcançado este marco.', 66),
('Aceita e segue regras nos jogos de mesa','Pergunte aos cuidadores se a criança é capaz de aceitar e seguir regras dos jogos de mesa.', 72),
('Copia um quadrado','Forneça à criança um lápis e uma folha de papel (sem pauta). Mostre a ela o desenho de um quadrado. Não nomear a figura nem mover seu dedo ou o lápis para demonstrar como desenhá-la. Peça para a criança “Faça um desenho como este!”. Podem ser fornecidas três tentativas. Se a criança for incapaz de copiar o quadrado da ficha, mostre a ela como fazê-lo, desenhando dois lados opostos (paralelos) e depois os outros dois lados opostos (em vez de desenhar o quadrado com um movimento contínuo). Três demonstrações e tentativas podem ser fornecidas.', 72),
('Define 7 palavras','Procedimento semelhante ao item “Define cinco palavras”. Agora deve definir 7 palavras.', 72),
('Equilibra-se em cada pé por 7 segundos','Procedimento semelhante a “Equilibra-se em cada pé 1 segundo” com o tempo de 7 segundos ou mais.', 72);